### ISSUE TITLE
how do build project in linux ?

### ISSUE THREAD

**Issue by matheuscamarques** [alfons-utfpr/Invasao-Alienigena---Jogo-de-plataforma-2D-com-SFML#1]
Hey friends :), if you can release a linux version I'll be one of the first to test it

**Comment by alfons-utfpr** [comment]
Fala Matheus! Usamos no projeto dois sistemas operacionais Windows e Ubuntu, pra rodar no Linux você pode utilizar o builder meson com o arquivo meson.build, que possuem instruções de uso no GitHub do Lucas Skora nos exercícios de técnicas de programação, o jogo não está nada completo foi feito pensando em cumprir os requisitos necessários para o projeto de técnicas da programação. Qualquer dúvida pode me contatar no discord ALFONS#4158.

**Comment by matheuscamarques** [comment]
tks!
